racketscript-extras/racketscript/htdp/universe.rkt
- fixes #20
- fixes Firefox hyphen issue
There may still be some issues but I tested it on all our example games.
=> use non-deprecated KeyboardEvent methods

racketscript-compiler/racketscript/compiler/expand.rkt
Not 100% sure but `expand` [seems to already apply `namespace-syntax-introduce`](http://docs.racket-lang.org/reference/Expanding_Top-Level_Forms.html?q=expand#%28def._%28%28quote._~23~25kernel%29._expand%29%29)?
All the tests still pass if we take it out, and other example programs seem to work as well.
=> remove unneeded namespace-syntax-introduce

racketscript-compiler/racketscript/compiler/runtime/core/numbers.js, racketscript-compiler/racketscript/compiler/runtime/core/vector.js, racketscript-compiler/racketscript/compiler/runtime/kernel.js, racketscript-compiler/racketscript/compiler/runtime/unsafe.js, tests/racket-core/list.rkt, tests/racket-core/racket-list.rkt, tests/racket-core/testing.rkt
- to support rest of racket/list, we need:
- with-handlers
- optional and kw args
- procedure-arity-includes and friends
Other edits:
- fix makeInit to return Vector instead of Array
- Numbers.add missing initial 0
- make-sequence needs extra arg for Racket >= 6.7.0.4
=> add remaining (currently supported) list tests

racketscript-compiler/racketscript/compiler/runtime/core/lib.js, racketscript-compiler/racketscript/compiler/runtime/core/ports.js, racketscript-compiler/racketscript/compiler/runtime/kernel.js, racketscript-compiler/racketscript/compiler/runtime/kernel.rkt, racketscript-compiler/racketscript/compiler/runtime/lib.rkt, tests/basic/char.rkt, tests/basic/format.rkt, tests/basic/port.rkt, tests/basic/string.rkt
1. Fixes the assembler to compare to `!== false` in `if` statements.
This fixes the behaviour of various functions such as `and`, `if`,
and `cond` to match Racket, where `#f` is the only "falsy" value.
**Update:** This change has been removed from this PR, see https://github.com/vishesh/racketscript/pull/73#discussion_r135356677
2. Adds support for `~x` to `format`.
3. Fixes `error` argument formatting.
4. Fixes the default contract check message.
5. Allows passing an `out` argument to `display`, `newline`, and `print`.
6. Adds basic implementations of the following functions:
* `string-ref`
* `make-string`
* `list->string`
* `char?` and `char` comparison functions
* `char->integer`
* `open-output-string`, `get-output-string`, and `string-port?`
This actually makes Waxeye work (the …
=> Various fixes and improvements

tests/fixture.rkt, tests/optimize/tail-sum.rkt
The `tests/optimize/tail-sum.rkt` integration test is failing for me when optimizations are off.
Should the tests in `tests/optimize` be run when there are no optimizations enabled?
ps - Loving the activity in this repo.
=> dont run optimize tests when optimizations are off

racketscript-compiler/racketscript/compiler/expand.rkt
Breaks for 6.4, while works for 6.10 #82
=> expand: fix wrong parsing of symbol in syntax/parser

racketscript-compiler/racketscript/compiler/runtime/core/equality.js, racketscript-compiler/racketscript/compiler/runtime/core/hash.js, racketscript-compiler/racketscript/compiler/runtime/core/hashing.js, racketscript-compiler/racketscript/compiler/runtime/core/marks.js, racketscript-compiler/racketscript/compiler/runtime/core/mpair.js, racketscript-compiler/racketscript/compiler/runtime/core/pair.js, racketscript-compiler/racketscript/compiler/runtime/core/struct.js, racketscript-compiler/racketscript/compiler/runtime/kernel.rkt, racketscript-compiler/racketscript/compiler/transform.rkt, tests/basic/list.rkt
* Adds a singleton class for Empty.
* Makes `list?` O(1) instead of O(n).
* Makes `length` checked.
* Makes `immutable?` work on lists.
* Makes the `_listLength` field always a number so it's more JIT-friendly.
* Avoids the expensive `instanceof` checks in `Pair.check` and `MPair.check`.
* Adds hash code caching for `Pair` and `MPair`.
* Fixes the `listFind` predicate check.
* Minor improvements to `makeList` and `listFromArray`.
* Removes the unused `_listLength` function.
* Removes the now unnecessary Array equality and hashing from `isEqual` and `hashForEqual`.
* Removes `cons?` and `empty?` from kernel as they are not a part of the Kernel in racket.
* Adds more tests.
@vishes Hoping for a quick turnaround on this so I can proceed with extracting the rest of the mega-PR.
=> List improvements

racketscript-compiler/racketscript/compiler/runtime/core/box.js, racketscript-compiler/racketscript/compiler/runtime/core/bytes.js, racketscript-compiler/racketscript/compiler/runtime/core/char.js, racketscript-compiler/racketscript/compiler/runtime/core/check.js, racketscript-compiler/racketscript/compiler/runtime/core/equality.js, racketscript-compiler/racketscript/compiler/runtime/core/hash.js, racketscript-compiler/racketscript/compiler/runtime/core/hashing.js, racketscript-compiler/racketscript/compiler/runtime/core/keyword.js, racketscript-compiler/racketscript/compiler/runtime/core/lib.js, racketscript-compiler/racketscript/compiler/runtime/core/marks.js, racketscript-compiler/racketscript/compiler/runtime/core/mpair.js, racketscript-compiler/racketscript/compiler/runtime/core/numbers.js, racketscript-compiler/racketscript/compiler/runtime/core/pair.js, racketscript-compiler/racketscript/compiler/runtime/core/ports.js, racketscript-compiler/racketscript/compiler/runtime/core/primitive.js, racketscript-compiler/racketscript/compiler/runtime/core/struct.js, racketscript-compiler/racketscript/compiler/runtime/core/symbol.js, racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js, racketscript-compiler/racketscript/compiler/runtime/core/values.js, racketscript-compiler/racketscript/compiler/runtime/core/vector.js, racketscript-compiler/racketscript/compiler/runtime/kernel.js, racketscript-compiler/racketscript/compiler/runtime/kernel.rkt, racketscript-compiler/racketscript/compiler/runtime/paramz.js, racketscript-compiler/racketscript/compiler/transform.rkt, tests/basic/list.rkt
* Replaces tabs with spaces throughout.
* Add spaces around import braces as per most style guides (Google, AirBnb).
* Fix indentation for statements such as `switch` etc.
* Spaces around default parameters.
Now is good time as there are no outstanding PRs, nor JS runtime work-in-progress that I'm aware of.
Note that this is based on #108 which I assume will get merged by the time you get to this.
You can then rebase this PR with a single click.
GitHub doesn't show tabs vs spaces by default, but you can use this bookmarklet to review: https://gist.github.com/glebm/5b6c4517322193fbc51090dc3b57a44a
```
javascript:(function()%7Bfunction%20e(e%2Co%2Cr)%7Bconst%20c%3De.nodeValue.split(%22%5Ct%22).map(e%3D%3Ee.split(%22%20%22))%3Bif(1%3D%3D%3Dc.length%26%261%3D%3D%3Dc%5B0%5D.length)return%3Bcons …
```
=> Reformat JS: Replace tabs with spaces

.gitignore, Makefile, package-lock.json, package.json
Currently fails to run due to some issues with the type signatures but they're fixed in #96.
=> A `make tscheck` task to typecheck the JS runtime

racketscript-compiler/racketscript/compiler/runtime/core/char.js, racketscript-compiler/racketscript/compiler/runtime/core/raw_hashing.js
A follow-up to #102
It's kinda useless to run it on the entire project, as unlike actual TypeScript types, JSDoc types are not powerful enough to express our contracts. However, I found that it helps a lot to run it on individual files while developing (still catches a ton of issues).
=> A minor fix to JSDoc types to make tscheck run

.eslintrc, racketscript-compiler/racketscript/compiler/runtime/core.js, racketscript-compiler/racketscript/compiler/runtime/core/box.js, racketscript-compiler/racketscript/compiler/runtime/core/bytes.js, racketscript-compiler/racketscript/compiler/runtime/core/char.js, racketscript-compiler/racketscript/compiler/runtime/core/check.js, racketscript-compiler/racketscript/compiler/runtime/core/equality.js, racketscript-compiler/racketscript/compiler/runtime/core/hash.js, racketscript-compiler/racketscript/compiler/runtime/core/hashing.js, racketscript-compiler/racketscript/compiler/runtime/core/keyword.js, racketscript-compiler/racketscript/compiler/runtime/core/lib.js, racketscript-compiler/racketscript/compiler/runtime/core/marks.js, racketscript-compiler/racketscript/compiler/runtime/core/mpair.js, racketscript-compiler/racketscript/compiler/runtime/core/numbers.js, racketscript-compiler/racketscript/compiler/runtime/core/pair.js, racketscript-compiler/racketscript/compiler/runtime/core/ports.js, racketscript-compiler/racketscript/compiler/runtime/core/primitive.js, racketscript-compiler/racketscript/compiler/runtime/core/raw_hashing.js, racketscript-compiler/racketscript/compiler/runtime/core/regexp.js, racketscript-compiler/racketscript/compiler/runtime/core/struct.js, racketscript-compiler/racketscript/compiler/runtime/core/symbol.js, racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js, racketscript-compiler/racketscript/compiler/runtime/core/values.js, racketscript-compiler/racketscript/compiler/runtime/core/vector.js, racketscript-compiler/racketscript/compiler/runtime/kernel.js, racketscript-compiler/racketscript/compiler/runtime/paramz.js
.eslintrc changes:
* Disallow dangling commas as they do not always work in NodeJS.
* Allow `~` by default as it is not likely to be a typo.
* Allow leading underscores by default when called via `this`, e.g.
`this._private_prop`.
* Allow use-before-define for functions. It is safe as function
declarations are hoisted, and we do it throughout the codebase.
* Allow generator loops (`for ... of`), as we do not target older
browsers that do not support them (AirBnB bans them by default because
the polyfill is too heavy).
There are still some lint errors but they will need to be fixed /
ignored manully.
=> Update .eslintrc `make eslint-fix`

racketscript-compiler/racketscript/compiler/runtime/core/lib.js
Using objects as maps is dangerous and leads to hard-to-debug cases.
E.g. consider what happens if someone puts `"hasOwnProperty"` as a key.
Actual `Map`s are also slightly faster in most modern browsers.
=> internedMake: Use a Map instead of Object

racketscript-compiler/racketscript/compiler/runtime/core/box.js, racketscript-compiler/racketscript/compiler/runtime/core/bytes.js, racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js
Fixes a bug introduced in #115.
`var` got hoisted even if the `if` check failed, resulting in undefined TextEncoder/Decoder.
Also fixes a missing import in box.js.
=> Fix TextEncoder/Decoder in browsers

racketscript-compiler/racketscript/compiler/runtime/paramz.js, tests/wcm/parameter-set.rkt
The previous version made it impossible to parameterize to false, 0, etc.
Also adds handling for `getCurrentParametrization()` returning false.
=> Fix parameterize to false'ish values.

racketscript-extras/racketscript/htdp/image.rkt, racketscript-extras/racketscript/htdp/universe.rkt, racketscript-extras/racketscript/private/jscommon.rkt
HTDP got broken after changes after improvements to identifier normalization improvements (expect more breaks :( in future around code that use FFI).
I'm putting this on CR to get some feedback on how to handle `this` stuff in JavaScript in future from RacketScript. Its not a safe thing to use, and particularly when you are using it in a callback. What this patch does is to extend[1] lambda's bind `this` with a variable, which will make it safe to use in callbacks and so.
Should we encourage something like this in our FFI  whenever `this` is involved? There will always be raw low-level `this` available if one actually needs that.
[1] https://github.com/vishesh/racketscript/compare/develop...task/fix-htdp-libs?expand=1#diff-6a9c6fd3ed8118a4107bf70798eb983bR47
@stchang @glebm
=> Fix broken HTDP libs

racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js, racketscript-compiler/racketscript/compiler/runtime/kernel.rkt, tests/basic/string.rkt
Adds a basic `string->number` implementation.
Does not support prefix forms ("#b101") nor arguments other than `radix`.
=> string->number support

package-lock.json, racketscript-compiler/racketscript/compiler/js-support/babel-webpack/package.json, racketscript-compiler/racketscript/compiler/js-support/babel/package.json, racketscript-compiler/racketscript/compiler/js-support/closure-compiler/package.json, racketscript-compiler/racketscript/compiler/js-support/traceur/package.json
Updates Gulp version and top-level `package.lock`.
=> Fix NPM security audit warnings

racketscript-compiler/racketscript/compiler/js-support/traceur/gulpfile.js, racketscript-compiler/racketscript/compiler/runtime/core/char.js, racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js, racketscript-compiler/racketscript/compiler/runtime/kernel.rkt, tests/basic/char.rkt
1. All `char-*?` Unicode property test methods.
2. `char-upcase` and `char-downcase`.
Fixes #170
=> Implement more char functions

Makefile, tests/fixture.rkt
`glob` pkg is deprecated, using `file/glob` instead
=> switch to file/glob

tests/racket-core/hash.rkt
Sorry, tests were still broken. with this commit, they should be fixed for 8.0 and 8.1
=> fix tests for racket 8.0 (hash-set and vs and/c)

Makefile, package.json
We don't need them because:
1. JSHint is out of date. We can use ESLint for linting javascript
code
2. TypeScript is useful but to use it we need to add types. Without them,
we can't rely on TS checks.
=> delete jshint and ts

.github/workflows/racket.yml, racketscript-compiler/racketscript/compiler/util-untyped.rkt, tests/racket-core/hash.rkt
- this fixes the tests when using Racket HEAD, see #200
- was previously breaking due to new use of "encoded paths" in links.rktd
- see racket commit 2ac7e21ad422ee322daa4a7e0db318f9b72b6c48
=> switch to using `links` fn (from setup/link) to process collection links

racketscript-compiler/racketscript/compiler/expand.rkt, racketscript-compiler/racketscript/compiler/main.rkt, racketscript-compiler/racketscript/compiler/moddeps.rkt, racketscript-compiler/racketscript/compiler/nothing.rkt, tests/fixture.rkt
Currently, we relied on a stub "nothing.rkt", but we should instead look at the
imported modules itself. This should fix the the 'undefined identifier' issues
we keep getting in Playground.
FIXES #134
=> Prepare proper module dependency graph when taking module from stdin

racketscript-compiler/racketscript/interop.rkt
js-object? is a useful function for js integrations so I think it's better to provide it. And we need to check if `v` is not null because:
```js
typeof null // object
```
and I did the same with `js-array?`. And replaced `instanceof` with `Array.isArray` (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs_isarray)
=> feat: provide `js-object?` and fix it

racketscript-compiler/racketscript/interop.rkt
Without the fix it works like that:
```lisp
(js-object? ($/obj (test "test"))) // #t
(js-object? "test") // #t
```
=> fix: check if js object is not a racket primitive

racketscript-compiler/racketscript/compiler/runtime/core/numbers.js, racketscript-compiler/racketscript/compiler/runtime/kernel.rkt, tests/basic/arithmatic.rkt
These [bitwise operators](https://docs.racket-lang.org/reference/generic-numbers.html#%28part._.Bitwise_.Operations%29) were missing from kernel.rkt. Adds tests to `basic/arithmatic/rkt`.
=> Adds bitwise-and, bitwise-ior, bitwise-xor, bitwise-not

racketscript-compiler/racketscript/compiler/runtime/kernel.rkt, tests/basic/vector.rkt
Fixes #252.
Previously, if the default value provided to `make-vector` was falsey, the vector would be populated with `0`. Now this will only happen if the default value is `undefined`.
If we wanted to enable a developer to populate a vector with `undefined`, we'd have to be able to detect if a value was passed in to the function or not. We could do so by accessing `arguments` directly if we feel like this is something a user should be able to do. 
As an addendum, even though `kernel.rkt` is enormous, might still be good to create a test submodule and throw things in there as people modify it.
=> Allow for `#f` default value

racketscript-compiler/racketscript/compiler/runtime/core/struct.js, racketscript-compiler/racketscript/compiler/runtime/kernel.rkt
Adds `prop:sealed` as a struct type property, as well as implementing its semantics (no other struct type can have a sealed struct type as super). 
This property is used in the expander linklet.
=> `prop:sealed` support

racketscript-compiler/racketscript/lang/reader.rkt, tests/ffi/for-array.rkt
This PR adds the ability to use `#lang racketscript`. It's the same as doing `#lang racketscript/base` for now but can be extended later. This closes issue #242. 
I couldn't come up with a way to test `#lang racketscript` by itself in a way that cleanly fit the 'tests' folder organization. Instead I changed the `#lang racketscript/base` in 'tests/ffi/for-array.rkt' to `#lang racketscript` and confirmed that the test still passed. If there's a better way of testing this, please let me know.
=> Add #lang racketscript

racketscript-compiler/racketscript/compiler/main.rkt, tests/dep-cache/has-dependency.rkt, tests/dep-cache/private/dependency.rkt
Fixes the issue where a stale dependency is not recompiled if the dependent file hasn't changed. It does this by checking all cached timestamps for stale files before the main compilation loop, instead of doing it in flight.
This resolves issue #313.
I'm having some trouble writing a test case for this code. There's a difference between the main compiler and the test fixture that causes this issue to crop up in tests despite the fix.  When using `racks`, this fix produces the desired behavior. I'll push another commit and update this pull request once I have a working test case.
=> Fix stale dependency compilation issue.

.github/workflows/racket.yml, racketscript-compiler/racketscript/compiler/runtime/kernel.rkt, racketscript-compiler/racketscript/compiler/transform.rkt
This PR adds support for Racket 8.7. The issue ended up being some unimplemented functions:
- procedure-arity-mask
- bitwise-bit-set?
- prop:object-name
I also reordered the `cond` expression in `transform.rkt`. I put `empty?` before `list?` because it seemed like the transformation to IL otherwise wouldn't use `Pair.EMPTY`. It wasn't causing any issues but it just didn't seem like the intended behavior.
=> Add support for Racket 8.7

racketscript-compiler/racketscript/compiler/main.rkt, racketscript-compiler/racketscript/compiler/transform.rkt, racketscript-compiler/racketscript/compiler/util.rkt
Fixes a bug where the private/interop module was copied to the build directory if a source file required racketscript/interop.
The racketscript/private/interop module includes the #%js-ffi function which raises an error if used in Racket. The compiler overrides this binding with js-ffi calls, so the module never actually needs to be copied to the build directory.
=> Fix unnecessary copy to build directory

racketscript-compiler/racketscript/compiler/main.rkt, racketscript-compiler/racketscript/compiler/runtime/unsafe.rkt, racketscript-compiler/racketscript/compiler/transform.rkt, racketscript-compiler/racketscript/compiler/util.rkt
Fixes issue #324 where the racket playground wouldn't compile. Specifically, it fixes a small bug in the implementation of unsafe division. Closes #324 
It also fixes issue #326 by reverting commit https://github.com/racketscript/racketscript/commit/4dc26bae5b896da6b02d28861e47b5393739141e which attempted to prevent unnecessary copying of the `private/interop.rkt` file to the build directory. This seems to cause a bug that wasn't caught by the Racketscript test suite. Closes #326
=> Fix Playground compilation issue (#324)
