racketscript/racketscript

- racketscript-compiler/racketscript/compiler/expand.rkt
- racketscript-compiler/racketscript/compiler/runtime/core/numbers.js
- racketscript-compiler/racketscript/compiler/runtime/kernel.js
- tests/racket-core/list.rkt
- tests/racket-core/racket-list.rkt
- tests/racket-core/testing.rkt
- support more of racket list tests
- fix andmap with mult lists
- support #%variable-reference
- add (stable) sort
- start support for (list) sequences
> add more list prims and list tests

- racketscript-compiler/racketscript/compiler/runtime/kernel.js
- tests/racket-core/list.rkt
- tests/racket-core/racket-list.rkt
- dont create box with single-arg call to values
- delete duplicate reverse
> add more Racket list tests; various other fixes

- racketscript-compiler/racketscript/compiler/runtime/core/bytes.js
- racketscript-extras/racketscript/htdp/image.rkt
- racketscript-extras/racketscript/htdp/private/color.rkt
- racketscript-extras/racketscript/htdp/universe.rkt
- racketscript-extras/racketscript/private/jscommon.rkt
- tests/basic/bytes.rkt
hdtp API still accepts Racket strings so that doesn't change, but internally it now has to pass native strings to JS APIs.
> Fixes hdtp to pass native strings to JS

- .travis.yml
Ahead of its becoming an LTS release a few months from now.
Fixes #101
> Switch to only supporting Node 8

- racketscript-compiler/racketscript/compiler/runtime/core.js
- racketscript-compiler/racketscript/compiler/runtime/core/lib.js
- racketscript-compiler/racketscript/compiler/runtime/core/procedure.js
> Move procedure-related functions to procedure.js

- .eslintrc
- Makefile
- package-lock.json
- package.json
As per #111, this project now uses the AirBnb JavaScript style guide but with 4 spaces for indentation.
This configures the project using the official AirBnb eslint configuration and adds an eslint-fix task that can fix some of the issues.
> .eslintrc and `make eslint-fix`

- .travis.yml
- racketscript-compiler/info.rkt
- racketscript-compiler/racketscript/compiler/js-support/babel-webpack/gulpfile.js
- racketscript-compiler/racketscript/compiler/js-support/babel/gulpfile.js
- racketscript-compiler/racketscript/compiler/js-support/closure-compiler/gulpfile.js
- racketscript-compiler/racketscript/compiler/js-support/traceur/gulpfile.js
- tests/fixture.rkt
I didnt add the version dependencies yet but just opening this pr to see if tests pass.
> fix tests for Racket v6.x

- racketscript-compiler/racketscript/compiler/js-support/traceur/gulpfile.js
The following tasks did not complete: '<anonymous>'
Did you forget to signal async completion?
> Signal asynchronous code done

- racketscript-compiler/racketscript/compiler/js-support/babel/gulpfile.js
- racketscript-compiler/racketscript/compiler/js-support/babel/package.json
Issue was outdated gulp/babel build files.
> build: Fixes babel build

- racketscript-compiler/racketscript/compiler/config.rkt
- racketscript-compiler/racketscript/compiler/expand.rkt
- racketscript-compiler/racketscript/compiler/runtime/core.js
- racketscript-compiler/racketscript/compiler/runtime/linklet-primitive.rkt
- racketscript-compiler/racketscript/compiler/runtime/unsafe.rkt
- racketscript-compiler/racketscript/compiler/transform.rkt
`#%variable-reference` implementation not really working.
> Enough to compiler the expander.

- .eslintrc
- package-lock.json
- package.json
- racketscript-compiler/racketscript/compiler/runtime/core.js
- racketscript-compiler/racketscript/compiler/runtime/core/bytes.js
- racketscript-compiler/racketscript/compiler/runtime/core/char.js
- racketscript-compiler/racketscript/compiler/runtime/core/check.js
- racketscript-compiler/racketscript/compiler/runtime/core/correlated.js
- racketscript-compiler/racketscript/compiler/runtime/core/errors.js
- racketscript-compiler/racketscript/compiler/runtime/core/hamt.js
- racketscript-compiler/racketscript/compiler/runtime/core/hash.js
- racketscript-compiler/racketscript/compiler/runtime/core/keyword.js
- racketscript-compiler/racketscript/compiler/runtime/core/linklet.js
- racketscript-compiler/racketscript/compiler/runtime/core/marks.js
- racketscript-compiler/racketscript/compiler/runtime/core/mpair.js
- racketscript-compiler/racketscript/compiler/runtime/core/path.js
- racketscript-compiler/racketscript/compiler/runtime/core/ports.js
- racketscript-compiler/racketscript/compiler/runtime/core/print_native_string.js
- racketscript-compiler/racketscript/compiler/runtime/core/print_ustring.js
- racketscript-compiler/racketscript/compiler/runtime/core/printing.js
- racketscript-compiler/racketscript/compiler/runtime/core/procedure.js
- racketscript-compiler/racketscript/compiler/runtime/core/struct.js
- racketscript-compiler/racketscript/compiler/runtime/core/symbol.js
- racketscript-compiler/racketscript/compiler/runtime/core/unicode_string.js
- racketscript-compiler/racketscript/compiler/runtime/core/vector.js
- racketscript-compiler/racketscript/compiler/runtime/kernel.js
- racketscript-compiler/racketscript/compiler/runtime/paramz.js
1. Add eslint into devDependencies.
2. Fix all autofixable issues.
3. Fix or ignore some other issues + add TODOs to fix them later.
4. Make some issues warnings because their fixing can lead to huge
refactoring.
> fix: update eslint config to avoid rules we don't follow

- .github/workflows/racket.yml
- add timeout
- delete racket 6.9
- add racket 8.0
> add timeout-minutes to avoid endless tests on Racket 8.*

- racketscript-compiler/racketscript/compiler/runtime/kernel.rkt
- tests/racket-core/hash.rkt
> add hash-strong?

- tests/fixture.rkt
It should help to avoid issues like that https://github.com/vishesh/racketscript/issues/195
> return a correct exit code on tests fail

- racketscript-compiler/racketscript/compiler/runtime/core/char.js
- tests/hash/eq-basic.rkt
- tests/hash/eqv-basic.rkt
- tests/racket-core/hash.rkt
- tests/racket-core/list.rkt
> actually fix tests for racket 8.x

- racketscript-compiler/racketscript/compiler/expand.rkt
- racketscript-compiler/racketscript/compiler/runtime/core.js
- racketscript-compiler/racketscript/compiler/runtime/core/bytes.js
- racketscript-compiler/racketscript/compiler/runtime/core/correlated.js
- racketscript-compiler/racketscript/compiler/runtime/core/errors.js
- racketscript-compiler/racketscript/compiler/runtime/core/print_native_string.js
- racketscript-compiler/racketscript/compiler/runtime/flfxnum.rkt
- racketscript-compiler/racketscript/compiler/runtime/kernel.js
- racketscript-compiler/racketscript/compiler/runtime/kernel.rkt
- racketscript-compiler/racketscript/compiler/runtime/unsafe.rkt
- tests/basic/bytes.rkt
- tests/basic/list.rkt
- tests/racket-core/testing.rkt
- tests/testing.rkt
these are needed to compile the playground examples (with webpack target), see:
- https://github.com/vishesh/racketscript-playground/issues/17
- https://github.com/vishesh/racketscript/pull/208
- https://github.com/vishesh/racketscript-playground/pull/18
> add a bunch of primitives

- racketscript-compiler/racketscript/boot/lang/private/interop.rkt
- racketscript-compiler/racketscript/interop.rkt
Add some unit tests for the two JS interop modules.
Add some tests & code coverage while I'm spelunking through parts of the codebase.
> Tests for interop

- racketscript-doc/info.rkt
- racketscript-doc/racketscript/info.rkt
- racketscript-doc/racketscript/scribblings/ffi.scrbl
- racketscript-doc/racketscript/scribblings/racketscript.scrbl
- racketscript-doc/racketscript/scribblings/start.scrbl
- racketscript/info.rkt
Just a stub at the moment
UPDATE: rough draft of `racketscript/interop`: https://stchang.github.io/racketscript/
> start docs

- README.md
> badges badges badges!

- racketscript-compiler/racketscript/compiler/main.rkt
After #314 was merged, I noticed when the compiler finished it would print a list of compiled modules to standard out, which is unintended behavior. This PR fixes the issue.
In this PR I also took the opportunity to refactor the `(racket->js)` method.
> Fix unintended printing of module paths to stdout

- racketscript-extras/racketscript/htdp/universe.rkt
Response to issue https://github.com/racketscript/racketscript/issues/299
> added name handler to rs/htdp/universe big-bang
